
name = input("Enter name : ")
pronoun1 = input("he or she: ")
pronoun2 = input("his or her: ")
celebrity = input("Enter a celebrity name: ")
celebrity_pronoun = input("him or her: ")
favorite_color = input("Enter favorite color: ")
favorite_teacher = input("Enter favorite teacher's name: ")
street_name = input("Enter a random street name: ")
favorite_pet = input("Enter favorite pet: ")
best_friend = input("Enter best friend: ")
favorite_drink = input("Enter favorite drink: ")
favorite_hobby = input("Enter favorite hobby: ")
favorite_song = input("Enter favorite song: ")
print(name + " was just minding " + pronoun2 + " business until one day while walking down " + street_name + " " + pronoun1)
print("Saw " + celebrity + ". " + name + " Instantly fainted just by looking at " + celebrity_pronoun + ". When " + name)
print("woke up " + pronoun1 + " didn't know where " + pronoun1 + " was. " + name + " looked up and saw " + pronoun1)
print("was in " + favorite_teacher + "'s lap. " + favorite_teacher + " offered " + name + " " + favorite_drink)
print("and " + name + " accepted the kind offer. " + name + " got back on " + pronoun2 + " walk with " + favorite_teacher)
print("but then they saw " + name + "'s pet " + favorite_pet + ". " + pronoun1 + " didn't know why it was out in the middle")
print("of the " + favorite_color + " street but " + pronoun1 + " had to go grab it. When they finally got")
print(favorite_pet + " it bit " + name + "'s anus so " + pronoun1 + " poured the " + favorite_drink + " on it to cool it")
print("off. That made " + pronoun2 + " anus feel way better. At the end of the day " + name + ", " + favorite_teacher)
print("," + favorite_pet + ", and " + celebrity + " were all " + favorite_hobby + " while " + best_friend + " was")
print("singing " + favorite_song + ".")